export const complaints = [
  {
    id: 'GRV-2026-001',
    title: 'Pothole on MG Road causing accidents',
    description: 'There is a large pothole near MG Road junction that has caused multiple accidents in the past week.',
    category: 'Roads & Infrastructure',
    department: 'Public Works Department',
    urgency: 'High',
    status: 'Assigned',
    location: 'MG Road, Sector 12',
    citizenId: 'user-001',
    citizenName: 'Rahul Sharma',
    citizenEmail: 'citizen@demo.com',
    supervisorId: 'supervisor-001',
    confidence: 0.92,
    createdAt: '2026-02-20',
    updatedAt: '2026-02-21',
  },
  {
    id: 'GRV-2026-002',
    title: 'Water supply disruption in Block C',
    description: 'No water supply for the past 3 days in Block C residential area.',
    category: 'Water Supply',
    department: 'Water Resources Department',
    urgency: 'High',
    status: 'Pending',
    location: 'Block C, Sector 5',
    citizenId: 'user-001',
    supervisorId: 'supervisor-001',
    confidence: 0.88,
    createdAt: '2026-02-19',
    updatedAt: '2026-02-19',
  },
  {
    id: 'GRV-2026-003',
    title: 'Streetlights not working in Sector 8',
    description: 'Multiple streetlights are non-functional in Sector 8 creating safety concerns at night.',
    category: 'Electricity',
    department: 'Electricity Department',
    urgency: 'Medium',
    status: 'In Progress',
    location: 'Sector 8, Main Market',
    citizenId: 'user-002',
    supervisorId: 'supervisor-001',
    confidence: 0.85,
    createdAt: '2026-02-18',
    updatedAt: '2026-02-20',
  },
  {
    id: 'GRV-2026-004',
    title: 'Garbage not collected for a week',
    description: 'Garbage has not been collected from our locality for over a week. Health hazard increasing.',
    category: 'Sanitation',
    department: 'Municipal Corporation',
    urgency: 'High',
    status: 'Assigned',
    location: 'Nehru Nagar, Ward 12',
    citizenId: 'user-001',
    supervisorId: 'supervisor-002',
    confidence: 0.91,
    createdAt: '2026-02-17',
    updatedAt: '2026-02-18',
  },
  {
    id: 'GRV-2026-005',
    title: 'Broken drainage system causing flooding',
    description: 'The drainage system near the main market is broken, causing waterlogging during rains.',
    category: 'Drainage',
    department: 'Public Works Department',
    urgency: 'High',
    status: 'Pending',
    location: 'Main Market, Sector 3',
    citizenId: 'user-002',
    supervisorId: null,
    confidence: 0.87,
    createdAt: '2026-02-16',
    updatedAt: '2026-02-16',
  },
  {
    id: 'GRV-2026-006',
    title: 'Noise pollution from construction site',
    description: 'Excessive noise from illegal construction happening after 10 PM in residential area.',
    category: 'Pollution',
    department: 'Environment Department',
    urgency: 'Medium',
    status: 'Resolved',
    location: 'Green Valley, Sector 15',
    citizenId: 'user-001',
    supervisorId: 'supervisor-002',
    confidence: 0.79,
    createdAt: '2026-02-14',
    updatedAt: '2026-02-22',
  },
  {
    id: 'GRV-2026-007',
    title: 'Public park in disrepair',
    description: 'The public park in Sector 10 has broken benches, overgrown grass, and non-functional fountains.',
    category: 'Parks & Recreation',
    department: 'Municipal Corporation',
    urgency: 'Low',
    status: 'Assigned',
    location: 'Central Park, Sector 10',
    citizenId: 'user-002',
    supervisorId: 'supervisor-001',
    confidence: 0.83,
    createdAt: '2026-02-13',
    updatedAt: '2026-02-15',
  },
  {
    id: 'GRV-2026-008',
    title: 'Illegal encroachment on public land',
    description: 'Shops have been illegally constructed on public footpath near bus stand.',
    category: 'Encroachment',
    department: 'Revenue Department',
    urgency: 'Medium',
    status: 'In Progress',
    location: 'Bus Stand Area, Sector 1',
    citizenId: 'user-003',
    supervisorId: 'supervisor-002',
    confidence: 0.76,
    createdAt: '2026-02-11',
    updatedAt: '2026-02-19',
  },
  {
    id: 'GRV-2026-009',
    title: 'Broken traffic signal at main intersection',
    description: 'Traffic signal at the main intersection has been non-functional for 2 days causing traffic jams.',
    category: 'Traffic',
    department: 'Traffic Police Department',
    urgency: 'High',
    status: 'Resolved',
    location: 'Main Intersection, Sector 6',
    citizenId: 'user-003',
    supervisorId: 'supervisor-001',
    confidence: 0.94,
    createdAt: '2026-02-10',
    updatedAt: '2026-02-12',
  },
  {
    id: 'GRV-2026-010',
    title: 'Contaminated drinking water',
    description: 'Residents are reporting stomach ailments due to contaminated drinking water supply.',
    category: 'Water Supply',
    department: 'Water Resources Department',
    urgency: 'High',
    status: 'Pending',
    location: 'Old Town, Ward 5',
    citizenId: 'user-001',
    supervisorId: null,
    confidence: 0.90,
    createdAt: '2026-02-09',
    updatedAt: '2026-02-09',
  },
  {
    id: 'GRV-2026-011',
    title: 'School building needs renovation',
    description: 'Government school building in Sector 7 has cracks and leaking roof posing danger to students.',
    category: 'Education',
    department: 'Education Department',
    urgency: 'High',
    status: 'Assigned',
    location: 'Govt School, Sector 7',
    citizenId: 'user-002',
    supervisorId: 'supervisor-002',
    confidence: 0.86,
    createdAt: '2026-02-08',
    updatedAt: '2026-02-10',
  },
  {
    id: 'GRV-2026-012',
    title: 'Stray animal menace in residential area',
    description: 'Large number of stray dogs in the colony causing fear among residents, especially children.',
    category: 'Animal Control',
    department: 'Municipal Corporation',
    urgency: 'Medium',
    status: 'Pending',
    location: 'Rose Garden Colony',
    citizenId: 'user-003',
    supervisorId: null,
    confidence: 0.81,
    createdAt: '2026-02-07',
    updatedAt: '2026-02-07',
  },
  {
    id: 'GRV-2026-013',
    title: 'Public toilet facility unhygienic',
    description: 'Public toilet near bus stand is in extremely unhygienic condition with no water supply.',
    category: 'Sanitation',
    department: 'Municipal Corporation',
    urgency: 'Medium',
    status: 'Resolved',
    location: 'Bus Stand, Sector 1',
    citizenId: 'user-001',
    supervisorId: 'supervisor-001',
    confidence: 0.88,
    createdAt: '2026-02-05',
    updatedAt: '2026-02-15',
  },
  {
    id: 'GRV-2026-014',
    title: 'Road divider damaged after accident',
    description: 'Road divider on NH-48 near toll plaza is damaged after a truck accident, creating risk.',
    category: 'Roads & Infrastructure',
    department: 'National Highways Authority',
    urgency: 'High',
    status: 'In Progress',
    location: 'NH-48, Toll Plaza',
    citizenId: 'user-002',
    supervisorId: 'supervisor-002',
    confidence: 0.93,
    createdAt: '2026-02-03',
    updatedAt: '2026-02-20',
  },
  {
    id: 'GRV-2026-015',
    title: 'Pension delayed for 3 months',
    description: 'Old age pension has not been credited for the last 3 months despite multiple visits to office.',
    category: 'Social Welfare',
    department: 'Social Welfare Department',
    urgency: 'High',
    status: 'Assigned',
    location: 'District Office',
    citizenId: 'user-003',
    supervisorId: 'supervisor-001',
    confidence: 0.84,
    createdAt: '2026-02-01',
    updatedAt: '2026-02-05',
  },
];
export const categories = [
  'Roads & Infrastructure',
  'Water Supply',
  'Electricity',
  'Sanitation',
  'Drainage',
  'Pollution',
  'Parks & Recreation',
  'Encroachment',
  'Traffic',
  'Education',
  'Animal Control',
  'Social Welfare',
];
export const statusOptions = ['Pending', 'Assigned', 'In Progress', 'Resolved'];
export const urgencyOptions = ['Low', 'Medium', 'High'];
