export const workers = [
    {
        id: 'worker-001',
        name: 'Ramesh Kumar',
        role: 'Electrician',
        department: 'Electricity Department',
        phone: '+91 98765 43210',
        activeTasks: 2,
        completedTasks: 18,
        totalTasks: 20,
        avgResolutionTime: 14, 
        status: 'Active',
        joinedAt: '2025-06-15',
    },
    {
        id: 'worker-002',
        name: 'Suresh Yadav',
        role: 'Electrician',
        department: 'Electricity Department',
        phone: '+91 98765 43211',
        activeTasks: 5,
        completedTasks: 12,
        totalTasks: 17,
        avgResolutionTime: 22,
        status: 'Overloaded',
        joinedAt: '2025-08-20',
    },
    {
        id: 'worker-003',
        name: 'Dinesh Meena',
        role: 'Electrician',
        department: 'Electricity Department',
        phone: '+91 98765 43212',
        activeTasks: 1,
        completedTasks: 25,
        totalTasks: 26,
        avgResolutionTime: 10,
        status: 'Active',
        joinedAt: '2025-03-10',
    },
    {
        id: 'worker-004',
        name: 'Prakash Singh',
        role: 'Line Inspector',
        department: 'Electricity Department',
        phone: '+91 98765 43213',
        activeTasks: 3,
        completedTasks: 8,
        totalTasks: 11,
        avgResolutionTime: 30,
        status: 'Active',
        joinedAt: '2025-09-01',
    },
    {
        id: 'worker-005',
        name: 'Anil Verma',
        role: 'Electrician',
        department: 'Electricity Department',
        phone: '+91 98765 43214',
        activeTasks: 0,
        completedTasks: 15,
        totalTasks: 15,
        avgResolutionTime: 12,
        status: 'Active',
        joinedAt: '2025-04-22',
    },
];
export const supervisorComplaints = [
    {
        id: 'GRV-2026-101',
        title: 'Frequent power cuts in Sector 8',
        description: 'Residents face daily power outages lasting 3-4 hours during peak hours. Transformer appears overloaded.',
        category: 'Electricity',
        department: 'Electricity Department',
        urgency: 'High',
        status: 'Pending',
        location: 'Sector 8, Main Market',
        citizenName: 'Priya Patel',
        confidence: 0.92,
        assignedWorker: null,
        assignedAt: null,
        resolvedAt: null,
        createdAt: '2026-02-25T10:30:00',
        slaDeadline: '2026-02-27T10:30:00',
    },
    {
        id: 'GRV-2026-102',
        title: 'Exposed electrical wires near school',
        description: 'Dangerous exposed wires hanging low near the government school entrance. Immediate attention required.',
        category: 'Electricity',
        department: 'Electricity Department',
        urgency: 'High',
        status: 'Pending',
        location: 'Govt School, Sector 7',
        citizenName: 'Amit Kumar',
        confidence: 0.95,
        assignedWorker: null,
        assignedAt: null,
        resolvedAt: null,
        createdAt: '2026-02-25T08:15:00',
        slaDeadline: '2026-02-27T08:15:00',
    },
    {
        id: 'GRV-2026-103',
        title: 'Streetlights not working on main road',
        description: 'Multiple streetlights on the main road of Sector 12 have been non-functional for a week.',
        category: 'Electricity',
        department: 'Electricity Department',
        urgency: 'Medium',
        status: 'Assigned',
        location: 'Sector 12, Main Road',
        citizenName: 'Rahul Sharma',
        confidence: 0.88,
        assignedWorker: 'worker-001',
        assignedAt: '2026-02-24T14:00:00',
        resolvedAt: null,
        createdAt: '2026-02-24T09:00:00',
        slaDeadline: '2026-02-26T09:00:00',
    },
    {
        id: 'GRV-2026-104',
        title: 'Transformer sparking at night',
        description: 'The transformer near Rose Garden Colony sparks at night, posing fire risk.',
        category: 'Electricity',
        department: 'Electricity Department',
        urgency: 'High',
        status: 'Assigned',
        location: 'Rose Garden Colony',
        citizenName: 'Sunita Devi',
        confidence: 0.91,
        assignedWorker: 'worker-003',
        assignedAt: '2026-02-24T16:30:00',
        resolvedAt: null,
        createdAt: '2026-02-24T11:00:00',
        slaDeadline: '2026-02-26T11:00:00',
    },
    {
        id: 'GRV-2026-105',
        title: 'Billing discrepancy complaint',
        description: 'Electricity bill shows 3x the usual amount. Meter readings appear incorrect.',
        category: 'Electricity',
        department: 'Electricity Department',
        urgency: 'Medium',
        status: 'In Progress',
        location: 'Nehru Nagar',
        citizenName: 'Vikram Singh',
        confidence: 0.78,
        assignedWorker: 'worker-002',
        assignedAt: '2026-02-23T10:00:00',
        resolvedAt: null,
        createdAt: '2026-02-22T15:00:00',
        slaDeadline: '2026-02-24T15:00:00',
    },
    {
        id: 'GRV-2026-106',
        title: 'Voltage fluctuation damaging appliances',
        description: 'Severe voltage fluctuations in Sector 5 causing damage to electrical appliances.',
        category: 'Electricity',
        department: 'Electricity Department',
        urgency: 'High',
        status: 'Resolved',
        location: 'Block C, Sector 5',
        citizenName: 'Meena Kumari',
        confidence: 0.86,
        assignedWorker: 'worker-003',
        assignedAt: '2026-02-20T09:00:00',
        resolvedAt: '2026-02-21T15:00:00',
        createdAt: '2026-02-19T14:00:00',
        slaDeadline: '2026-02-21T14:00:00',
    },
    {
        id: 'GRV-2026-107',
        title: 'Electric pole tilting dangerously',
        description: 'An electric pole near bus stand area is tilting at a dangerous angle after recent storms.',
        category: 'Electricity',
        department: 'Electricity Department',
        urgency: 'High',
        status: 'Resolved',
        location: 'Bus Stand Area',
        citizenName: 'Rajesh Gupta',
        confidence: 0.93,
        assignedWorker: 'worker-001',
        assignedAt: '2026-02-18T08:00:00',
        resolvedAt: '2026-02-19T11:00:00',
        createdAt: '2026-02-17T16:00:00',
        slaDeadline: '2026-02-19T16:00:00',
    },
    {
        id: 'GRV-2026-108',
        title: 'No electricity connection in new colony',
        description: 'New residential colony in Sector 15 has been waiting 2 months for electricity connection.',
        category: 'Electricity',
        department: 'Electricity Department',
        urgency: 'Medium',
        status: 'Pending',
        location: 'Green Valley, Sector 15',
        citizenName: 'Arun Tiwari',
        confidence: 0.82,
        assignedWorker: null,
        assignedAt: null,
        resolvedAt: null,
        createdAt: '2026-02-26T07:00:00',
        slaDeadline: '2026-02-28T07:00:00',
    },
    {
        id: 'GRV-2026-109',
        title: 'Meter box damaged by rain',
        description: 'External meter box is damaged and exposed to rain, creating electrical hazard.',
        category: 'Electricity',
        department: 'Electricity Department',
        urgency: 'Medium',
        status: 'Assigned',
        location: 'Old Town, Ward 5',
        citizenName: 'Kavita Sharma',
        confidence: 0.80,
        assignedWorker: 'worker-004',
        assignedAt: '2026-02-25T11:00:00',
        resolvedAt: null,
        createdAt: '2026-02-25T06:00:00',
        slaDeadline: '2026-02-27T06:00:00',
    },
    {
        id: 'GRV-2026-110',
        title: 'Underground cable fault',
        description: 'Underground cable fault causing intermittent power supply in Central Park area.',
        category: 'Electricity',
        department: 'Electricity Department',
        urgency: 'Low',
        status: 'Resolved',
        location: 'Central Park, Sector 10',
        citizenName: 'Deepak Jain',
        confidence: 0.75,
        assignedWorker: 'worker-005',
        assignedAt: '2026-02-15T09:00:00',
        resolvedAt: '2026-02-17T14:00:00',
        createdAt: '2026-02-14T10:00:00',
        slaDeadline: '2026-02-16T10:00:00',
    },
];
