export const users = [
    {
        id: 'user-001',
        name: 'Rahul Sharma',
        email: 'citizen@demo.com',
        password: 'password123',
        role: 'Citizen',
        aadhaar: '123456789012',
        avatar: null,
    },
    {
        id: 'user-002',
        name: 'Priya Patel',
        email: 'citizen2@demo.com',
        password: 'password123',
        role: 'Citizen',
        aadhaar: '234567890123',
        avatar: null,
    },
    {
        id: 'user-003',
        name: 'Amit Kumar',
        email: 'citizen3@demo.com',
        password: 'password123',
        role: 'Citizen',
        aadhaar: '345678901234',
        avatar: null,
    },
    {
        id: 'supervisor-001',
        name: 'Inspector Rajesh',
        email: 'supervisor@demo.com',
        password: 'password123',
        role: 'Ward Supervisor',
        aadhaar: '456789012345',
        avatar: null,
    },
    {
        id: 'supervisor-002',
        name: 'Ward Supervisor Sunita',
        email: 'supervisor2@demo.com',
        password: 'password123',
        role: 'Ward Supervisor',
        aadhaar: '567890123456',
        avatar: null,
    },
    {
        id: 'admin-001',
        name: 'Administrator Singh',
        email: 'admin-sathi@demo.com',
        password: 'password123',
        role: 'District Civic Administrator',
        aadhaar: '678901234567',
        avatar: null,
    },
];
